name: selenium_test
on: [push, pull_request]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  selenium_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      #----------------------------------------------
      #  -----  install browsers  -----
      #----------------------------------------------
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install Firefox
        uses: riccione/setup_firefox@v1
      - name: Check Chromium version
        run: chromium-browser --version
      - name: Test with pytest and generate allure report
        run: |
          pytest tests --alluredir=allure-results
        continue-on-error: true